Hangman/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HangmanGame.urls'))
]

HangmanGame/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views.Jogo import Jogo

app_name = 'HangmanGame'

urlpatterns = [
    path('', Jogo.as_view(), name="home"),
    path('iniciar', Jogo.as_view(), name="iniciar"),
    path('continuar', Jogo.as_view(), name="continuar"),
    path('entrar', LoginView.as_view()),
    path('sair', LogoutView.as_view()),
]

HangmanGame/models/Palavra.py
from django.db import models
from django.contrib.auth.models import User
import re


class Palavra(models.Model):
    descricao = models.CharField('Descrição da palavra', max_length=254, unique=True)
    comentario = models.TextField('Comentário, informações adicionais', blank=True)
    registrado = models.DateField('Data de registro', auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def mostrar_letras_encontradas(self, letras):
        """Esconde letras com '_', caso a letra não esteja no parametro de array letras

        Retorna por exemplo: Para a palavra "Tempo", caso tenha passado o valor ['e', 'o'], o resultado será "_emp_".

        """
        return re.sub('[^%s\s\-]' % ''.join(letras), '_', self.descricao)

    def __str__(self):
        return self.descricao

HangmanGame/models/Partida.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from .Palavra import Palavra
from .Perfil import Perfil
from unidecode import unidecode
import re


class Partida(models.Model):
    jogador = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    palavra = models.ForeignKey(Palavra, on_delete=models.CASCADE)
    sessao = models.ForeignKey(Session, on_delete=models.CASCADE, null=True)
    inicio = models.DateTimeField('Início da partida', auto_now_add=True)
    ultimo_acesso = models.DateTimeField('Última vez que o jogador jogou a partida', auto_now=True)
    errou = models.SmallIntegerField('Quantas vezes o jogador errou as letras', default=0)
    letras = models.CharField('Letras que foram jogadas', max_length=26)
    ganhou = models.BooleanField(null=True)

    def adivinhar_letra(self, letra):

        if letra in self.letras or not letra.isalpha() or len(letra) != 1 or self.ganhou is not None:
            return

        letra = self.normalizar_texto(letra)

        if letra not in self.palavra_normalizada():
            self.errou += 1

        self.contabilizar_inicio_partida_perfil()

        self.letras += letra

        if self.errou >= 6:
            self.perdeu()
        elif '_' not in self.palavra_descoberta:
            self.venceu()

    def adivinhar_palavra(self, palavra):

        palavra = self.normalizar_texto(palavra)

        if palavra == '' or self.ganhou is not None:
            return

        self.contabilizar_inicio_partida_perfil()

        if palavra == self.palavra_normalizada():
            self.venceu()
        else:
            self.perdeu()

    def get_letras_utilizadas(self):

      return list(self.letras)

    def venceu(self):

        self.ganhou = True
        self.contabilizar_partida_no_perfil()

    def perdeu(self):

        self.ganhou = False
        self.contabilizar_partida_no_perfil()

    def criar_perfil(self):

        perfil = Perfil(usuario=self.jogador)
        perfil.save()
        return perfil

    def contabilizar_inicio_partida_perfil(self):

        if len(self.letras) is 0:
            perfil = self.perfil_do_jogador()

            if perfil is not None:
                perfil.jogos += 1
                perfil.save()

    def contabilizar_partida_no_perfil(self):

        perfil = self.perfil_do_jogador()

        if perfil:
            if self.ganhou:
                perfil.venceu += 1
            else:
                perfil.perdeu += 1
            perfil.save()

    def perfil_do_jogador(self):
        if self.jogador is None:
            return None

        perfil = Perfil.objects.filter(usuario=self.jogador).first()

        if perfil is None:
            return self.criar_perfil()
        return perfil

    @property
    def palavra_descoberta(self):

        palavra_original = self.palavra.descricao
        sem_pontuacao_palavra = re.sub('[^%s_\-0-9]' % self.letras, '_', unidecode(palavra_original.lower()))
        letras_palavra = list(sem_pontuacao_palavra)

        for indice, letra in enumerate(letras_palavra):
            if letra != '_':
                letras_palavra[indice] = palavra_original[indice]

        return str.join('', letras_palavra)

    def palavra_normalizada(self):
        return self.normalizar_texto(self.palavra.descricao)

    def nova_palavra(self):
        from random import randint
        total = Palavra.objects.count()
        self.palavra = Palavra.objects.all()[randint(0, total - 1)]

    def iniciou(self):
        return self.errou > 0

    def acabou(self):
        return self.ganhou != None

    @staticmethod
    def normalizar_texto(texto):
        return unidecode(texto.strip().lower())

    @classmethod
    def criar_randomica(cls, usuario, sessao):

        from random import randint

        total = Palavra.objects.count()
        palavra_selecionada = Palavra.objects.all()[randint(0, total - 1)]

        sessao_encontrada = Session.objects.filter(session_key=sessao.session_key).first()

        if usuario is not None:
            perfil_encontrado = Perfil.objects.filter(usuario=usuario).first()
            if perfil_encontrado is None:
                perfil = Perfil(usuario=usuario)
                perfil.save()

        return cls(jogador=usuario, palavra=palavra_selecionada, sessao=sessao_encontrada)

    def __str__(self):
        return 'jogador {0}, palavra: {1}, quantidade de tentativas que errou: {2}, id: {3}'.format(self.jogador, self.palavra.descricao, self.errou, self.id)

    def save(self):
        self.letras = str.join('', sorted(self.get_letras_utilizadas()))
        super().save()

HangmanGame/models/Perfil.py
from django.db import models
from django.contrib.auth.models import User


class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, editable=False)
    jogos = models.IntegerField(default=0)
    perdeu = models.IntegerField(default=0)
    venceu = models.IntegerField(default=0)

    def __str__(self):
        return 'perfil de %s' % self.usuario.get_username();

HangmanGame/views/Jogo.py
from django.views.decorators.cache import cache_page
from django.views.generic import View
from django.http import HttpResponse
from django.shortcuts import render
from ..models import Partida

class Jogo(View):

    def get(self, request):

        partida_id = request.GET.get('partida')

        partida_id = partida_id if partida_id else request.session.get('partida-id')

        usuario = request.user if request.user.is_authenticated else None

        if partida_id != None:
            try:
                partida = Partida.objects.get(pk=partida_id)
                if not partida.iniciou():
                    partida.nova_palavra()
                    partida.save()
                if partida.acabou():
                    raise Partida.DoesNotExist()

            except Partida.DoesNotExist:
                del request.session['partida-id']
                partida = Partida.criar_randomica(usuario=usuario, sessao=request.session)
                partida.save()
                request.session['partida-id'] = partida.id
        else:
            partida = Partida.criar_randomica(usuario=usuario, sessao=request.session)
            partida.save()
            request.session['partida-id'] = partida.id

        context = {
            'partida': partida,
        }

        return render(request, 'HangmanGame/jogo.html', context)


    def post(self, request):
        partida_id = request.POST.get('partida-id')

        partida_id = partida_id if partida_id is not '' else request.session.get('partida-id')

        if partida_id is not '':
            partida_encontrada = Partida.objects.filter(pk=partida_id).first()

            if partida_encontrada.jogador != None:

                usuario_autenticado = request.user

                if usuario_autenticado != partida_encontrada.jogador:
                    return HttpResponse(status=401)

        tentativa_letra = request.POST.get('tentativa-letra')
        tentativa_palavra = request.POST.get('tentativa-palavra')

        if tentativa_letra == '' and tentativa_palavra == '':
            return render(request, 'HangmanGame/jogo.html', {'partida': partida_encontrada})


        partida_encontrada.adivinhar_letra(letra=tentativa_letra[:1])

        partida_encontrada.adivinhar_palavra(palavra=tentativa_palavra)

        partida_encontrada.save()

        return render(request, 'HangmanGame/jogo.html', {'partida': partida_encontrada})

HangmanGame/templates/HangmanGame/jogo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js" crossorigin="anonymous"></script>
    <title>Jogo da forca</title>
    {% load compress %}{% compress css %}<style>
    #palavra-descoberta
    {
        letter-spacing: 14px;
        font-size: 500%;
        color: #d1d1d1;
    }
    .custom-grid
    {
        border-bottom: 2px solid #eee;
        margin: 7px 0;
        font-size: 28px;
        color: #9e9e9e;
    }
    </style>{% endcompress %}
</head>
<body class="grey lighten-5">
<div class="container center-align">
    <div class="row">
        <div class="col s12 custom-grid center-align">
            <span class="flow-text">Jogo da Forca</span>
        </div>
    </div>
    <div class="row">
        <span class="flow-text">
            <svg width="110" height="270" version="1.1" xmlns="http://www.w3.org/2000/svg">
                <line id="corda" x1="50" x2="50" y1="0" y2="40" stroke="#000" stroke-width="4" aria-label="Corda"/>
                <circle id="cabeca" class="hide" cx="50" cy="80" r="40" stroke="#000" fill="transparent" stroke-width="4" aria-label="Cabeça"/>
                <line id="corpo" class="hide" x1="50" x2="50" y1="120" y2="200" stroke="#000" stroke-width="5" aria-label="Corpo"/>
                <line id="mao-esquerda" class="hide" x1="50" x2="5" y1="120" y2="170" stroke="#000" stroke-width="5" aria-label="Mão esquerda"/>
                <line id="mao-direita" class="hide" x1="50" x2="100" y1="120" y2="170" stroke="#000" stroke-width="5" aria-label="Mão direita"/>
                <line id="perna-direita" class="hide" x1="50" x2="100" y1="198" y2="260" stroke="#000" stroke-width="5" aria-label="Perna direita"/>
                <line id="perna-esquerda" class="hide" x1="50" x2="0" y1="198" y2="260" stroke="#000" stroke-width="5" aria-label="Perna esquerda"/>
            </svg>
        </span>
    </div>
    <div class="row">
        <div class="row">
            <div class="col s12 x12">
                {% if partida.ganhou is None %}
                <div id="palavra-descoberta">{{ partida.palavra_descoberta }}</div>
                {% elif partida.ganhou is not None %}
                <div id="palavra-descoberta">{{ partida.palavra.descricao }}</div>
                {% endif %}
            </div>
        </div>
        {% if partida.ganhou is True %}
            <h1>Você ganhou!</h1>
            <div class="row s12">
             <a class="btn waves-effect grey lighten-0" href="{% url 'HangmanGame:iniciar' %}">
                <i class="material-icons right">fiber_new</i> Novo jogo
              </a>
            </div>
        {% elif partida.ganhou is False %}
            <h1>Você perdeu!</h1>
            <div class="row s12">
             <a class="btn waves-effect grey lighten-0" href="{% url 'HangmanGame:iniciar' %}">
                <i class="material-icons right">fiber_new</i> Novo jogo
              </a>
            </div>
        {% else %}
            <div class="row">
                <div class="col x12 l6 offset-l3 m12">
                    <form method="post" action="{% url 'HangmanGame:iniciar' %}" autocomplete="off" >
                        {% csrf_token %}
                        <input type="hidden" name="partida-id" value="{{ partida.id }}" />
                        <div class="row">
                            <div class="input-field col l1 s12">
                              <input id="letra" type="text" class="validate tooltipped" name="tentativa-letra"
                              data-position="bottom" maxlength="1"
                                     data-tooltip="Tentar letra" onkeydown="AllowLettersOnly(event);" onkeyup="AllowLettersOnly(event);" autofocus>
                              <label for="letra">Letra</label>
                            </div>
                            <div class="col l1 s6 offset-s3">Ou</div>
                            <div class="input-field col l10 s12">
                              <input id="palavra" type="text" class="validate tooltipped" name="tentativa-palavra" maxlength="{{ partida.palavra.descricao | length }}"
                              data-position="bottom" data-tooltip="Tentar palavra completa" onkeydown="AllowLettersOnly(event);" onkeyup="AllowLettersOnly(event);">
                              <label for="palavra">Palavra</label>
                            </div>
                          </div>
                        <div class="row s12">
                         <button class="btn waves-effect grey lighten-1" type="submit" name="enviar">Enviar
                            <i class="material-icons right">send</i>
                          </button>
                        </div>
                    </form>
                </div>
            </div>{% endif %}
    </div>
</div>
    {% load compress %}{% compress js%}<script>
    function AllowLettersOnly(e) {
        var keyCode = (e.keyCode ? e.keyCode : e.which);
        if(keyCode == 8 || keyCode == 186 || keyCode == 9 || keyCode == 13){
            return;
        }
        if (keyCode < 65 || keyCode > 90) {
            e.preventDefault();
        }
    }
    function montarCorpo(erros)
    {
        var cabeca = document.getElementById('cabeca');
        var corpo = document.getElementById('corpo');
        var maoEsquerda = document.getElementById('mao-esquerda');
        var maoDireita = document.getElementById('mao-direita');
        var pernaEsquerda = document.getElementById('perna-esquerda');
        var pernaDireita = document.getElementById('perna-direita');
        if(erros == 0)
        {
            var cssClassForHideElement = "hide";
            cabeca.className.baseVal = cssClassForHideElement;
            corpo.className.baseVal = cssClassForHideElement;
            maoEsquerda.className.baseVal = cssClassForHideElement;
            maoDireita.className.baseVal = cssClassForHideElement;
            pernaEsquerda.className.baseVal = cssClassForHideElement;
            pernaDireita.className.baseVal = cssClassForHideElement;
        }
        if(erros > 0 && erros < 7)
        {
            if(erros > 0)
            {
                cabeca.className.baseVal = "";
            }
            if(erros > 1)
            {
                corpo.className.baseVal = "";
            }
            if(erros > 2)
            {
                maoEsquerda.className.baseVal = "";
            }
            if(erros > 3)
            {
                maoDireita.className.baseVal = "";
            }
            if(erros > 4)
            {
                pernaEsquerda.className.baseVal = "";
            }
            if(erros > 5)
            {
                pernaDireita.className.baseVal = "";
            }
        }

        if(erros > 6)
        {
            for(var i = 1; i < 7; i++)
            {
                montarCorpo(i);
            }
        }
    }
    montarCorpo( {{ partida.errou }});
    {% if partida.ganhou == False %}
        montarCorpo(10);
    {% endif %}
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.tooltipped');
        M.Tooltip.init(elems, {});
    });
    </script>{% endcompress %}
</body>
</html>